### ISSUE TITLE
Mac OSX

### ISSUE THREAD

**Issue by Philelis** [jvenant/passff#47] opened 2014-11-19 20:23 UTC
The plugin doesn't work on Mac OSX

**Comment by nilsonholger** [comment] 2015-01-15 22:31
Indeed, `FileUtils.directorySeparator` only returns `undefined` and messes up the file location.
There's a quick hack I just did to fix this problem. You will need to edit the plugin. On OSX it is located in
`/Users/<USER>/Library/Application Support/Firefox/Profiles/<PROFILE>.default/extensions/passff@invicem.pro.xpi`.
Unzip it to some other location, e.g.: `mkdir passff; cd passff; unzip passff@invicem.pro.xpi`
Now edit `modules/preferences.js`, comment line 77 and add a new line below:

    //let filename = (gpgAgentInfo.indexOf(FileUtils.directorySeparator) != 0 ? this.home + FileUtils.directorySeparator : "") + gpgAgentInfo;
    let filename = gpgAgentInfo;

Now zip it back up: `zip -r passff@invicem.pro.xpi *` and replace the original plugin with your quickfixed/hacked version.

This procedure will set the `filename` for the gpg agent info file search to the string provided by the config dialog. It is **important** that you now put the full path, e.g. `/Users/<USER>/.gnupg/gpg-agent.info` (since we just disabled the path assembling).
FYI, my `gpg-agent.info` contains: `GPG_AGENT_INFO=/tmp/gpg-<RANDOM>/S.gpg-agent:29097:1`

Restart and enjoy, that should be it (at least was for me ;-).

@jvenant Sorry for not providing a real fix/pull-request yet, I might look into it, if I find the time. But a quick glance at https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/FileUtils.jsm revealed that there is no FileUtils.directorySeparator, or am I mistaken on that?

**Comment by phryneas** [comment] 2015-01-17 18:12
I fear that I am to blame for the introduction of FileUtils.directorySeparator - I can confirm that at some point, it was in the documentation (wouldn't have found it otherwise) and worked (and still does on my Windows Firefox).

I will be looking into this the next days. Maybe something like "if the path already contains a '\', use '\' else use '/'" - in my experience passff was unusuable with the '/' on Windows could be used, although I don't find that very elegant.

**Comment by jvenant** [comment] 2015-01-22 09:20
This issue should be fixed in the last release [v1-pre-release-14](https://github.com/jvenant/passff/releases/tag/v1-pre-release-14)
I totally change the way paths are generated. Using a more standard approach.

Let me know if you face some issue with it.

**Comment by nilsonholger** [comment] 2015-01-22 12:52
Only did a quick glance over the code, don't know osfile.jsm, but it seems to run without any problems so far (Browser Console Log also didn't turn up anything fishy).

@jvenant Thanks a lot for the fix, very much appreciated.

**Comment by jvenant** [comment] 2015-01-23 08:05
OK, you're welcome :).
I close the ticket then.

About this, from gpg 2.1, .gpg-agent-info file and GPG_AGENT_INFO environment variable are no more required.
cf https://www.gnupg.org/faq/whats-new-in-2.1.html

**Comment by Philelis** [comment] 2015-02-03 09:17
Doesn't work... :(

timeout: Verbindungs-Zeitüberschreitung. Überprüfen Sie die Fehlerkonsole auf beiden Geräten auf mögliche Fehlermeldungen. Öffnen Sie die Web-Konsole erneut, um es noch einmal zu versuchen.
10:15:31.783 "[PassFF]" "Tab Selected" <tab crop="end" onerror="this.removeAttribute('image');" class="tabbrowser-tab" context="tabContextMenu" closetabtext="Tab schließen" linkedpanel="panel-3-9" afterselected-visible="true" last-visible-tab="true" label="Neuer Tab" visibleLabel="Neuer Tab"> bootstrap.js:266
10:15:31.785 "[PassFF]" "createContextualMenu" "about:newtab" menu.js:255
10:15:31.785 "[PassFF]" "Create children menu list" Array[0] undefined menu.js:262
10:15:31.786 TypeError: listElm is null menu.js:240
10:15:31.889 POST https://tiles.services.mozilla.com/v2/links/view [HTTP/1.1 200 OK 1023ms]
10:15:37.799 "[PassFF]" "Location changed" "about:addons" bootstrap.js:235
10:15:37.800 "[PassFF]" "createContextualMenu" "about:addons" menu.js:255
10:15:37.800 "[PassFF]" "Create children menu list" Array[0] undefined menu.js:262
10:15:37.800 listElm is null menu.js:240
10:15:37.841 "[PassFF]" "Location changed" "about:addons" bootstrap.js:235
10:15:37.841 "[PassFF]" "createContextualMenu" "about:addons" menu.js:255
10:15:37.841 "[PassFF]" "Create children menu list" Array[0] undefined menu.js:262
10:15:37.842 listElm is null menu.js:240
10:15:37.954 "[PassFF]" "Content loaded" load { isTrusted: true, eventPhase: 1, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 0, NONE: 0, CAPTURING_PHASE: 1, AT_TARGET: 2, BUBBLING_PHASE: 3 } false 0 bootstrap.js:243
10:15:40.980 "[PassFF]" "startup" bootstrap.js:35
10:15:40.983 "[PassFF]" "Try to retrieve Gpg agent variable from file /Users/Phil//.gpg-agent-info" preferences.js:77
10:15:40.984 "[PassFF]" "Preferences initialised" [object Object] preferences.js:39
10:15:40.985 "[PassFF]" "Execute pass" [object Object] pass.js:203
10:15:40.992 "[PassFF]" "Retrieve Gpg agent variable from file" preferences.js:83
10:15:40.993 "[PassFF]" "Set Gpg agent variable :" Array[4] preferences.js:85
10:15:41.513 A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Tue Feb 03 2015 10:15:31 GMT+0100 (CET)
Full Message: [object Object]

**Comment by jvenant** [comment] 2015-02-03 09:51
I'm very sorry to hear that :(
Anyway, It looks like you don't use the last version : the log line numbers don't match the current code.
Could you try with the very last version here : [v1-pre-release-18)](https://github.com/jvenant/passff/releases/tag/v1-pre-release-18)

Thank you very much for your perseverance

**Comment by Philelis** [comment] 2015-02-03 10:02
No button :/
This is from the newest version:
10:58:26.359 "[PassFF]" "Try to retrieve Gpg agent variable from file /Users/Phil/.gpg-agent-info" bootstrap.js:32
10:58:26.361 "[PassFF]" "Preferences initialised" Object { passwordInputNames: Array[3], loginInputNames: Array[4], loginFieldNames: Array[4], passwordFieldNames: Array[3], urlFieldNames: Array[2], command: "/usr/local/bin/pass", commandArgs: Array[1], home: "/Users/Phil", storeDir: "", storeGit: "", 6 weitere… } bootstrap.js:32
10:58:26.362 "[PassFF]" "Execute pass" Object { command: "/usr/local/bin/pass", arguments: Array[0], environment: Array[2], charset: "UTF-8", workdir: "/Users/Phil", mergeStderr: false, done: PassFF.Pass.executePass/params.done(data) } bootstrap.js:31
10:58:26.381 "[PassFF]" "Retrieve Gpg agent variable from file" bootstrap.js:32
10:58:26.381 "[PassFF]" "Set Gpg agent variable :" Array [ "GPG_AGENT_INFO=/Users/Phil/.gnupg/S.gpg-agent:5804:1", "SSH_AUTH_SOCK=/Users/Phil/.gnupg/S.gpg-agent.ssh", "SSH_AGENT_PID=5804", "" ] bootstrap.js:31

**Comment by jvenant** [comment] 2015-02-04 07:57
If you have a bash task using 100% of CPU, I think it means that for some reason, the pass script is in some kind of infinit loop.
You may try executing the exact same command (and with the same environment variables) than the one described in the "Execute pass" log line on a command line.
You may also try using GnuPG >= 2.1. Environment variables management drastically change in this version.

**Comment by nolith** [comment] 2015-03-02 10:06
Hello.
I've got the same problem, no button and 2 bashes using 99% CPU.

```
"[PassFF]" "Try to retrieve Gpg agent variable from file /Users/nolith/.gpg-agent-info" bootstrap.js:32
"[PassFF]" "Preferences initialised" Object { passwordInputNames: Array[3], loginInputNames: Array[4], loginFieldNames: Array[4], passwordFieldNames: Array[3], urlFieldNames: Array[2], command: "/usr/local/bin/pass", commandArgs: Array[1], home: "/Users/nolith", storeDir: "", storeGit: "", altri 7… } bootstrap.js:32
"[PassFF]" "Execute pass" Object { command: "/usr/local/bin/pass", arguments: Array[1], environment: Array[2], charset: "UTF-8", workdir: "/Users/nolith", mergeStderr: false, done: PassFF.Pass.executePass/params.done(), bufferedOutput: false, libc: "libc.dylib" } bootstrap.js:31
"[PassFF]" "Retrieve Gpg agent variable from file" bootstrap.js:32
"[PassFF]" "Set Gpg agent variable :" Array [ "GPG_AGENT_INFO=/tmp/gpg-yjcmJm/S.gp…", "SSH_AUTH_SOCK=/tmp/gpg-5KVCZI/S.gpg…", "SSH_AGENT_PID=378", "GNOME_KEYRING_CONTROL=", "PATH=/usr/bin:/bin:/usr/sbin:/sbin" ] bootstrap.js:31
```
I tried runing pass with the ENV specified in the "Execute pass" step and it works correctly. But if I had the variables detected in "Set Gpg agent variable" it will hangs:

```
$ GPG_AGENT_INFO=/tmp/gpg-yjcmJm/S.gpg-agent:378:1 SSH_AUTH_SOCK=/tmp/gpg-5KVCZI/S.gpg-agent.ssh SSH_AGENT_PID=378 GNOME_KEYRING_CONTROL="" PATH=/usr/bin:/bin:/usr/sbin:/sbin HOME=/Users/nolith DISPLAY=":0.0" /usr/local/bin/pass
/usr/local/bin/pass: line 298: /usr/local/bin/getopt: No such file or directory
```

If the PATH var is removed it will work.

Hope this will help.

**Comment by jvenant** [comment] 2015-03-02 10:12
Did you try the hack described in #55 :

> In the pass options, set
> "pass command" to "/bin/bash" and "pass command line arguments" to "--login /usr/local/bin/pass"

**Comment by nolith** [comment] 2015-03-02 10:41
That worked :dart: 

Thank you so much.

**Comment by jvenant** [comment] 2015-03-02 10:45
It's planned to execute pass through a shell instead of directly in a (near) future version.
I hope it will prevent us to manage all those env variables stuff.

But it's not implemented yet :wink:

**Closed** 2015-03-05 10:59 UTC
Labels: bug, Done
